apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
      initContainers:
        - name: db-migration
          image: backend-image
          args:
            - migrate
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backend-data
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-image
          resources:
            limits:
              memory: 1024Mi
              cpu: 500m
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-images
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location /images/ {
                auth_request /api/auth;

                root /data/nginx-static;
            }

            location = /api/auth {
                proxy_pass http://backend/api/auth/image;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-images
spec:
  selector:
    matchLabels:
      app: nginx-images
  template:
    metadata:
      labels:
        app: nginx-images
    spec:
      containers:
        - name: nginx-images
          image: nginx:1.21.1-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: images
              mountPath: /data
            - name: config
              mountPath: /etc/nginx
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: backend-data
        - name: config
          configMap:
            name: nginx-images
---
apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  selector:
    app: nginx-images
  ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              name: http
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              name: http
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: images
            port:
              name: http
