# Generated by Django 3.2.5 on 2021-08-19 14:55

import birthdays.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=birthdays.models.userAvatarDirectory)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
