apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "birthday-calendar.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
    {{- include "birthday-calendar.selectorLabels" . | nindent 4 }}
